p3_variables <- c("id_child", "id_pcg", "name_child", "dob_child",
                  "age_child", "gest_age_child", "name_pcg", "dob_pcg",
                  "age_pcg", "edd", "gest_age_mother", "trimester",
                  "visitor", "visit_date", "status", "prenatal", "dcs",
                  "relation", "race_pcg", "sex_pcg", "married", "partner",
                  "support", "unstbl_hsng", "employment", "gov_benefits",
                  "income", "education", "school", "transportation",
                  "uninsured_pcg", "medicaid_pcg", "private_pcg",
                  "psych_do", "poor_mhdays", "pcp_prep", "pcp_prep_opt",
                  "car_seat", "car_seat_opt", "safe_sleep_prep",
                  "screen_time", "food_barriers", "smoke_hhld", "drugs",
                  "drinks_avg", "drinks_max", "planned_preg",
                  "wt_pre_mother", "wt_gain", "wt_mother", "ht_mother",
                  "bmi_pre", "bmi", "chr_dz", "childbirths", "primigravida",
                  "ldd", "spacing", "spacing_plan", "preg_cx", "preg_cx_hx",
                  "diabetes_risk", "preg_outcome", "pnc_v", "pnc_vtot",
                  "pnc_date", "folic_acid", "folic_acid_date", "tdap",
                  "tdap_opt", "bf_plan", "bf_disch", "bf_status",
                  "smoke_mother", "cigs", "cigs_pre_preg", "cigs_1_tri",
                  "cigs_2_tri", "cigs_3_tri", "ecigs", "ecigs_preg",
                  "fruits", "vegetables", "wic_mother", "wic_mother_opt",
                  "phys_active", "lead_mother", "lead_tst_mother",
                  "dental_mother", "pp_exam", "pp_exam_opt",
                  "contraception", "toxo_risk", "race_child", "sex_child",
                  "uninsured_child", "medicaid_child", "chip_child",
                  "private_child", "wt_child", "len_child", "birth_cx",
                  "er_visits", "pcp", "well_child", "immz", "immz_opt",
                  "safe_sleep", "screen_time_hrs", "smoke_exp", "wic_child",
                  "wic_child_opt", "lead_child", "lead_tst_child",
                  "dental_child", "ed_neg", "ed_pos", "ref_d", "ref_a",
                  "review_date", "proc_days")

# Loaded with: devtools::use_data(p3_variables, internal = TRUE)
